#MySQL DataBase Configuration (MySQL+Hikari)
spring:
 datasource:
  url: jdbc:mysql:///shivdata
  driver-class-name: com.mysql.jdbc.Driver
  username: root
  password: shiv
  
  hikari:
   connection-timeout: 60000
   maximum-pool-size: 30